# Generated by Django 2.2.7 on 2019-12-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apteka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, unique=True)),
                ('adres', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('kraj_pochodzenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LogAutoryzacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=30)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('data_autoryzacji', models.DateTimeField(null=True, verbose_name='Czas ostatniej autoryzacji')),
            ],
        ),
        migrations.CreateModel(
            name='SubstancjaCzynna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_hasla', models.BinaryField(max_length=128)),
                ('sol_hasla', models.BinaryField(max_length=32)),
                ('login', models.CharField(max_length=30, unique=True)),
                ('poziom_dostepu', models.IntegerField(default=0)),
                ('apteki', models.ManyToManyField(to='pharmacy_app.Apteka')),
            ],
        ),
        migrations.CreateModel(
            name='Opakowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ile_dawek', models.IntegerField()),
                ('jednostka_dawki', models.IntegerField()),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Lek')),
            ],
        ),
        migrations.CreateModel(
            name='OpakowaniaApteki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('apteka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Apteka')),
                ('opakowanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Opakowanie')),
            ],
        ),
        migrations.AddField(
            model_name='lek',
            name='substancje_czynne',
            field=models.ManyToManyField(to='pharmacy_app.SubstancjaCzynna'),
        ),
    ]
