# Generated by Django 2.2.7 on 2019-12-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apteka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=30)),
                ('Adres', models.CharField(max_length=30)),
                ('Kod_pocztowy', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HASH_hasla', models.CharField(max_length=30)),
                ('LOGIN', models.CharField(max_length=30, unique=True)),
                ('Poziom_dostpu', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik_Apteka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apteka_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Apteka')),
                ('Pracownik_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Pracownik')),
            ],
        ),
    ]
