# Generated by Django 2.2.7 on 2019-12-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=30)),
                ('Kraj_poch', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_czynna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_czynna_Lek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lek_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Lek')),
                ('Sub_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Sub_czynna')),
            ],
        ),
        migrations.CreateModel(
            name='Opakowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ile_dawek', models.IntegerField(max_length=10)),
                ('Jednostka_dawki', models.IntegerField(max_length=10)),
                ('Lek_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_app.Lek')),
            ],
        ),
    ]
