# Generated by Django 2.2.7 on 2019-12-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=30)),
                ('Nazwsiko', models.CharField(max_length=30)),
                ('Adres', models.CharField(max_length=30)),
                ('Kod_pocztowy', models.CharField(max_length=30)),
                ('Data_ur', models.DateTimeField(verbose_name='urodzenia Data')),
                ('LOGIN', models.CharField(max_length=30)),
                ('HASH_hasa', models.CharField(max_length=30)),
            ],
        ),
    ]
