# Generated by Django 2.2.7 on 2019-12-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Klient',
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_zamowienia', models.DateTimeField(verbose_name='zamowienia data')),
                ('Klient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Klient')),
            ],
        ),
    ]
