# Generated by Django 2.2.7 on 2019-12-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_apteka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
