# Generated by Django 2.2.7 on 2019-12-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apteka',
        ),
    ]
